### ISSUE TITLE
Cannot find module 'babel/register'

### ISSUE THREAD

**Issue by veeracs** [insin/react-hn#65]
Wondering if we are missing babel dependencies. I get below error when I run `npm i && npm start`

```
⚡ npm start
> react-hn@1.5.0 start /Users/csekharveera/Sites/react-hn
> node server.js

module.js:440
    throw err;
    ^

Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/csekharveera/Sites/react-hn/server.js:8:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/csekharveera/.nvm/versions/node/v6.1.0/bin/node" "/Users/csekharveera/.nvm/versions/node/v6.1.0/bin/npm" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! react-hn@1.5.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-hn@1.5.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-hn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-hn
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-hn
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/csekharveera/Sites/react-hn/npm-debug.log
```

**Comment by addyosmani** [comment]
Try the https://github.com/insin/react-hn/tree/update-latest-deps branch. I'm going to PR that against master sometime soon, once I've cleaned up my commits.

**Comment by addyosmani** [comment]
Okay. This should now be fixed with master.
